# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!


target 'JSDemo' do

pod 'WebViewJavascriptBridge', '~> 6.0.2'

#pod 'JavaScriptBridge', '~> 0.3.1'

end
